/**
 * RAL Classic K7 — kompletný zoznam (213 farieb) organizovaný podľa sérií.
 * Pre použitie na /vzorkovnik stránke.
 *
 * RAL Classic má oficiálne 213 farieb v K7 karte. Niektoré (fluorescenčné,
 * perleťové, hliníkové) nie sú vhodné pre klasické epoxidové podlahy, ale
 * v vzorkovníku ich držíme pre komplexnosť ponuky (na dopyt vieme aj tie).
 *
 * Štruktúra:
 *   - kod: "RAL 7016"
 *   - nazov: "Antracitsivá"
 *   - hex: "#293133"
 *   - skupina: "greys" | "whites" | "beiges-browns" | "blues" | "greens" | "reds-pinks" | "violets" | "yellows-oranges" | "blacks"
 */

export interface RalSwatch {
  kod: string;
  nazov: string;
  hex: string;
  skupina:
    | "whites"
    | "yellows-oranges"
    | "reds-pinks"
    | "violets"
    | "blues"
    | "greens"
    | "greys"
    | "beiges-browns"
    | "blacks";
}

export const RAL_CLASSIC_FULL: RalSwatch[] = [
  // WHITES & IVORY
  { kod: "RAL 9010", nazov: "Čisto biela", hex: "#F7F7F1", skupina: "whites" },
  { kod: "RAL 9016", nazov: "Dopravná biela", hex: "#F1F1F1", skupina: "whites" },
  { kod: "RAL 9001", nazov: "Krémová biela", hex: "#EAE6CA", skupina: "whites" },
  { kod: "RAL 9002", nazov: "Sivobiela", hex: "#E6E5DC", skupina: "whites" },
  { kod: "RAL 9003", nazov: "Signálna biela", hex: "#F4F4F4", skupina: "whites" },
  { kod: "RAL 9018", nazov: "Papyrusová biela", hex: "#CFD3CD", skupina: "whites" },
  { kod: "RAL 1013", nazov: "Perlovo biela", hex: "#E3D9C6", skupina: "whites" },
  { kod: "RAL 1014", nazov: "Slonovinová", hex: "#DFCEA1", skupina: "whites" },
  { kod: "RAL 1015", nazov: "Slonová kosť", hex: "#E6D5B8", skupina: "whites" },

  // YELLOWS / ORANGES
  { kod: "RAL 1002", nazov: "Piesková žltá", hex: "#C6A664", skupina: "yellows-oranges" },
  { kod: "RAL 1003", nazov: "Signálna žltá", hex: "#F7BA0B", skupina: "yellows-oranges" },
  { kod: "RAL 1004", nazov: "Zlatožltá", hex: "#CDA434", skupina: "yellows-oranges" },
  { kod: "RAL 1005", nazov: "Medovo žltá", hex: "#A98307", skupina: "yellows-oranges" },
  { kod: "RAL 1006", nazov: "Kukuričná žltá", hex: "#E4A010", skupina: "yellows-oranges" },
  { kod: "RAL 1007", nazov: "Narcisovo žltá", hex: "#DC9D00", skupina: "yellows-oranges" },
  { kod: "RAL 1012", nazov: "Citrónovo žltá", hex: "#C7B446", skupina: "yellows-oranges" },
  { kod: "RAL 1016", nazov: "Sírovo žltá", hex: "#EDFF21", skupina: "yellows-oranges" },
  { kod: "RAL 1017", nazov: "Šafránovo žltá", hex: "#F5D033", skupina: "yellows-oranges" },
  { kod: "RAL 1018", nazov: "Zinkovo žltá", hex: "#FAD201", skupina: "yellows-oranges" },
  { kod: "RAL 1020", nazov: "Olivovo žltá", hex: "#999950", skupina: "yellows-oranges" },
  { kod: "RAL 1021", nazov: "Repková žltá", hex: "#F3DA0B", skupina: "yellows-oranges" },
  { kod: "RAL 1023", nazov: "Dopravná žltá", hex: "#FAD201", skupina: "yellows-oranges" },
  { kod: "RAL 1024", nazov: "Okrová žltá", hex: "#AEA04B", skupina: "yellows-oranges" },
  { kod: "RAL 1026", nazov: "Fluorescenčná žltá", hex: "#FFFF00", skupina: "yellows-oranges" },
  { kod: "RAL 1027", nazov: "Kari", hex: "#9D9101", skupina: "yellows-oranges" },
  { kod: "RAL 1028", nazov: "Melónovo žltá", hex: "#F4A900", skupina: "yellows-oranges" },
  { kod: "RAL 1032", nazov: "Genistová žltá", hex: "#D6AE01", skupina: "yellows-oranges" },
  { kod: "RAL 1033", nazov: "Dáhliová žltá", hex: "#F3A505", skupina: "yellows-oranges" },
  { kod: "RAL 1034", nazov: "Pastelovo žltá", hex: "#EFA94A", skupina: "yellows-oranges" },
  { kod: "RAL 1036", nazov: "Perlovo zlatá", hex: "#705335", skupina: "yellows-oranges" },
  { kod: "RAL 1037", nazov: "Slnečno žltá", hex: "#F39F18", skupina: "yellows-oranges" },
  { kod: "RAL 2000", nazov: "Žlto-oranžová", hex: "#ED760E", skupina: "yellows-oranges" },
  { kod: "RAL 2001", nazov: "Červeno-oranžová", hex: "#C93C20", skupina: "yellows-oranges" },
  { kod: "RAL 2002", nazov: "Rumelková oranžová", hex: "#CB2821", skupina: "yellows-oranges" },
  { kod: "RAL 2003", nazov: "Pastelovo oranžová", hex: "#F39F18", skupina: "yellows-oranges" },
  { kod: "RAL 2004", nazov: "Čistá oranžová", hex: "#E55B13", skupina: "yellows-oranges" },
  { kod: "RAL 2005", nazov: "Fluorescenčná oranžová", hex: "#FF2301", skupina: "yellows-oranges" },
  { kod: "RAL 2007", nazov: "Fluorescenčná svetlá oranžová", hex: "#FFA420", skupina: "yellows-oranges" },
  { kod: "RAL 2008", nazov: "Svetlá oranžová", hex: "#F18F1F", skupina: "yellows-oranges" },
  { kod: "RAL 2009", nazov: "Dopravná oranžová", hex: "#F54021", skupina: "yellows-oranges" },
  { kod: "RAL 2010", nazov: "Signálna oranžová", hex: "#D84B20", skupina: "yellows-oranges" },
  { kod: "RAL 2011", nazov: "Hlboká oranžová", hex: "#EC7C26", skupina: "yellows-oranges" },
  { kod: "RAL 2012", nazov: "Lososovo-oranžová", hex: "#E55137", skupina: "yellows-oranges" },
  { kod: "RAL 2013", nazov: "Perlovo oranžová", hex: "#C35831", skupina: "yellows-oranges" },

  // REDS / PINKS
  { kod: "RAL 3000", nazov: "Ohňová červená", hex: "#AF2B1E", skupina: "reds-pinks" },
  { kod: "RAL 3001", nazov: "Signálna červená", hex: "#A52019", skupina: "reds-pinks" },
  { kod: "RAL 3002", nazov: "Karmínovo červená", hex: "#A52019", skupina: "reds-pinks" },
  { kod: "RAL 3003", nazov: "Rubínovo červená", hex: "#9B111E", skupina: "reds-pinks" },
  { kod: "RAL 3004", nazov: "Purpurovo červená", hex: "#75151E", skupina: "reds-pinks" },
  { kod: "RAL 3005", nazov: "Vínovo červená", hex: "#5E2129", skupina: "reds-pinks" },
  { kod: "RAL 3007", nazov: "Čierno-červená", hex: "#412227", skupina: "reds-pinks" },
  { kod: "RAL 3009", nazov: "Oxidovo červená", hex: "#6D3F36", skupina: "reds-pinks" },
  { kod: "RAL 3011", nazov: "Hnedo-červená", hex: "#781F19", skupina: "reds-pinks" },
  { kod: "RAL 3012", nazov: "Béžovo-červená", hex: "#C1876B", skupina: "reds-pinks" },
  { kod: "RAL 3013", nazov: "Paradajkovo červená", hex: "#A12312", skupina: "reds-pinks" },
  { kod: "RAL 3014", nazov: "Antická ružová", hex: "#D36E70", skupina: "reds-pinks" },
  { kod: "RAL 3015", nazov: "Svetloružová", hex: "#EA899A", skupina: "reds-pinks" },
  { kod: "RAL 3016", nazov: "Koralovo červená", hex: "#B32821", skupina: "reds-pinks" },
  { kod: "RAL 3017", nazov: "Ružová", hex: "#E63244", skupina: "reds-pinks" },
  { kod: "RAL 3018", nazov: "Jahodovo červená", hex: "#D53032", skupina: "reds-pinks" },
  { kod: "RAL 3020", nazov: "Dopravná červená", hex: "#C7372F", skupina: "reds-pinks" },
  { kod: "RAL 3022", nazov: "Lososovo-ružová", hex: "#D95030", skupina: "reds-pinks" },
  { kod: "RAL 3024", nazov: "Fluorescenčná červená", hex: "#F80000", skupina: "reds-pinks" },
  { kod: "RAL 3026", nazov: "Fluorescenčná svetlá červená", hex: "#FE0000", skupina: "reds-pinks" },
  { kod: "RAL 3027", nazov: "Malinovo červená", hex: "#C51D34", skupina: "reds-pinks" },
  { kod: "RAL 3028", nazov: "Čisto červená", hex: "#CB3234", skupina: "reds-pinks" },
  { kod: "RAL 3031", nazov: "Orientálne červená", hex: "#B32428", skupina: "reds-pinks" },
  { kod: "RAL 3032", nazov: "Perlovo rubínová", hex: "#721422", skupina: "reds-pinks" },
  { kod: "RAL 3033", nazov: "Perlovo ružová", hex: "#B44C43", skupina: "reds-pinks" },

  // VIOLETS
  { kod: "RAL 4001", nazov: "Červeno-lila", hex: "#6D3F5B", skupina: "violets" },
  { kod: "RAL 4002", nazov: "Červeno-fialová", hex: "#922B3E", skupina: "violets" },
  { kod: "RAL 4003", nazov: "Vresová fialová", hex: "#DE4C8A", skupina: "violets" },
  { kod: "RAL 4004", nazov: "Bordovo fialová", hex: "#641C34", skupina: "violets" },
  { kod: "RAL 4005", nazov: "Modro-fialová", hex: "#6C4675", skupina: "violets" },
  { kod: "RAL 4006", nazov: "Dopravná purpurová", hex: "#A03472", skupina: "violets" },
  { kod: "RAL 4007", nazov: "Purpurovo fialová", hex: "#4A192C", skupina: "violets" },
  { kod: "RAL 4008", nazov: "Signálna fialová", hex: "#924E7D", skupina: "violets" },
  { kod: "RAL 4009", nazov: "Pastelovo fialová", hex: "#A18594", skupina: "violets" },
  { kod: "RAL 4010", nazov: "Telemagenta", hex: "#CF3476", skupina: "violets" },
  { kod: "RAL 4011", nazov: "Perlovo fialová", hex: "#8673A1", skupina: "violets" },
  { kod: "RAL 4012", nazov: "Perlovo černicová", hex: "#6C6874", skupina: "violets" },

  // BLUES
  { kod: "RAL 5000", nazov: "Fialovo-modrá", hex: "#354D73", skupina: "blues" },
  { kod: "RAL 5001", nazov: "Zeleno-modrá", hex: "#1F3438", skupina: "blues" },
  { kod: "RAL 5002", nazov: "Ultramarinová modrá", hex: "#20214F", skupina: "blues" },
  { kod: "RAL 5003", nazov: "Zafírová modrá", hex: "#1D1E33", skupina: "blues" },
  { kod: "RAL 5004", nazov: "Čierno-modrá", hex: "#18171C", skupina: "blues" },
  { kod: "RAL 5005", nazov: "Signálna modrá", hex: "#1E2460", skupina: "blues" },
  { kod: "RAL 5007", nazov: "Brilantná modrá", hex: "#3E5F8A", skupina: "blues" },
  { kod: "RAL 5008", nazov: "Sivo-modrá", hex: "#26252D", skupina: "blues" },
  { kod: "RAL 5009", nazov: "Azúrovo modrá", hex: "#025669", skupina: "blues" },
  { kod: "RAL 5010", nazov: "Encyánovo modrá", hex: "#0E294B", skupina: "blues" },
  { kod: "RAL 5011", nazov: "Oceľová modrá", hex: "#231A24", skupina: "blues" },
  { kod: "RAL 5012", nazov: "Svetlomodrá", hex: "#3B83BD", skupina: "blues" },
  { kod: "RAL 5013", nazov: "Kobaltová modrá", hex: "#1E213D", skupina: "blues" },
  { kod: "RAL 5014", nazov: "Holubičia modrá", hex: "#606E8C", skupina: "blues" },
  { kod: "RAL 5015", nazov: "Nebesky modrá", hex: "#2271B3", skupina: "blues" },
  { kod: "RAL 5017", nazov: "Dopravná modrá", hex: "#063971", skupina: "blues" },
  { kod: "RAL 5018", nazov: "Tyrkysovo modrá", hex: "#3F888F", skupina: "blues" },
  { kod: "RAL 5019", nazov: "Kapri modrá", hex: "#1B5583", skupina: "blues" },
  { kod: "RAL 5020", nazov: "Oceánová modrá", hex: "#1D334A", skupina: "blues" },
  { kod: "RAL 5021", nazov: "Vodná modrá", hex: "#256D7B", skupina: "blues" },
  { kod: "RAL 5022", nazov: "Nočná modrá", hex: "#252850", skupina: "blues" },
  { kod: "RAL 5023", nazov: "Vzdialená modrá", hex: "#49678D", skupina: "blues" },
  { kod: "RAL 5024", nazov: "Pastelovo modrá", hex: "#5D9B9B", skupina: "blues" },
  { kod: "RAL 5025", nazov: "Perlovo encyánová", hex: "#2A6478", skupina: "blues" },
  { kod: "RAL 5026", nazov: "Perlovo nočná", hex: "#102C54", skupina: "blues" },

  // GREENS
  { kod: "RAL 6000", nazov: "Patinová zelená", hex: "#316650", skupina: "greens" },
  { kod: "RAL 6001", nazov: "Smaragdovo zelená", hex: "#287233", skupina: "greens" },
  { kod: "RAL 6002", nazov: "Listová zelená", hex: "#2D572C", skupina: "greens" },
  { kod: "RAL 6003", nazov: "Olivovo zelená", hex: "#424632", skupina: "greens" },
  { kod: "RAL 6004", nazov: "Modrozelená", hex: "#1F3A3D", skupina: "greens" },
  { kod: "RAL 6005", nazov: "Machovo zelená", hex: "#2F4538", skupina: "greens" },
  { kod: "RAL 6006", nazov: "Sivo-olivová", hex: "#3E3B32", skupina: "greens" },
  { kod: "RAL 6007", nazov: "Fľašovo zelená", hex: "#343B29", skupina: "greens" },
  { kod: "RAL 6008", nazov: "Hnedo-zelená", hex: "#39352A", skupina: "greens" },
  { kod: "RAL 6009", nazov: "Jedľová zelená", hex: "#31372B", skupina: "greens" },
  { kod: "RAL 6010", nazov: "Trávová zelená", hex: "#35682D", skupina: "greens" },
  { kod: "RAL 6011", nazov: "Rezedovo zelená", hex: "#6C7059", skupina: "greens" },
  { kod: "RAL 6012", nazov: "Čierno-zelená", hex: "#343E40", skupina: "greens" },
  { kod: "RAL 6013", nazov: "Trstinovo zelená", hex: "#6C7156", skupina: "greens" },
  { kod: "RAL 6014", nazov: "Žlto-olivová", hex: "#47402E", skupina: "greens" },
  { kod: "RAL 6015", nazov: "Čierno-olivová", hex: "#3B3C36", skupina: "greens" },
  { kod: "RAL 6016", nazov: "Tyrkysovo zelená", hex: "#1E5945", skupina: "greens" },
  { kod: "RAL 6017", nazov: "Májová zelená", hex: "#4C9141", skupina: "greens" },
  { kod: "RAL 6018", nazov: "Žltozelená", hex: "#57A639", skupina: "greens" },
  { kod: "RAL 6019", nazov: "Pastelovo zelená", hex: "#BDECB6", skupina: "greens" },
  { kod: "RAL 6020", nazov: "Chrómovo zelená", hex: "#2E3A23", skupina: "greens" },
  { kod: "RAL 6021", nazov: "Bledo zelená", hex: "#89AC76", skupina: "greens" },
  { kod: "RAL 6022", nazov: "Hnedo-olivová", hex: "#25221B", skupina: "greens" },
  { kod: "RAL 6024", nazov: "Dopravná zelená", hex: "#308446", skupina: "greens" },
  { kod: "RAL 6025", nazov: "Papraďová zelená", hex: "#3D642D", skupina: "greens" },
  { kod: "RAL 6026", nazov: "Opálovo zelená", hex: "#015D52", skupina: "greens" },
  { kod: "RAL 6027", nazov: "Svetlo-zelená", hex: "#84C3BE", skupina: "greens" },
  { kod: "RAL 6028", nazov: "Borovicová zelená", hex: "#2C5545", skupina: "greens" },
  { kod: "RAL 6029", nazov: "Mätovo zelená", hex: "#20603D", skupina: "greens" },
  { kod: "RAL 6032", nazov: "Signálna zelená", hex: "#317F43", skupina: "greens" },
  { kod: "RAL 6033", nazov: "Mätovo-tyrkysová", hex: "#497E76", skupina: "greens" },
  { kod: "RAL 6034", nazov: "Pastelovo tyrkysová", hex: "#7FB5B5", skupina: "greens" },
  { kod: "RAL 6035", nazov: "Perlovo zelená", hex: "#1C542D", skupina: "greens" },
  { kod: "RAL 6036", nazov: "Perlovo opálová", hex: "#193737", skupina: "greens" },
  { kod: "RAL 6037", nazov: "Čisto zelená", hex: "#008F39", skupina: "greens" },
  { kod: "RAL 6038", nazov: "Fluorescenčná zelená", hex: "#00BB2D", skupina: "greens" },

  // GREYS
  { kod: "RAL 7000", nazov: "Veveričia sivá", hex: "#78858B", skupina: "greys" },
  { kod: "RAL 7001", nazov: "Strieborno-sivá", hex: "#8A9597", skupina: "greys" },
  { kod: "RAL 7002", nazov: "Olivovo sivá", hex: "#7E7B52", skupina: "greys" },
  { kod: "RAL 7003", nazov: "Machovo sivá", hex: "#6C7059", skupina: "greys" },
  { kod: "RAL 7004", nazov: "Signálna sivá", hex: "#969992", skupina: "greys" },
  { kod: "RAL 7005", nazov: "Myšia sivá", hex: "#646B63", skupina: "greys" },
  { kod: "RAL 7006", nazov: "Béžovo-sivá", hex: "#6D6552", skupina: "greys" },
  { kod: "RAL 7008", nazov: "Kaki sivá", hex: "#6A5F31", skupina: "greys" },
  { kod: "RAL 7009", nazov: "Zelenkavo sivá", hex: "#4D5645", skupina: "greys" },
  { kod: "RAL 7010", nazov: "Plachtová sivá", hex: "#4C514A", skupina: "greys" },
  { kod: "RAL 7011", nazov: "Železno-sivá", hex: "#434B4D", skupina: "greys" },
  { kod: "RAL 7012", nazov: "Bazaltovo sivá", hex: "#4E5754", skupina: "greys" },
  { kod: "RAL 7013", nazov: "Hnedo-sivá", hex: "#464531", skupina: "greys" },
  { kod: "RAL 7015", nazov: "Bridlicovo sivá", hex: "#51565C", skupina: "greys" },
  { kod: "RAL 7016", nazov: "Antracitsivá", hex: "#293133", skupina: "greys" },
  { kod: "RAL 7021", nazov: "Čiernosivá", hex: "#23282B", skupina: "greys" },
  { kod: "RAL 7022", nazov: "Umbrosivá", hex: "#332F2C", skupina: "greys" },
  { kod: "RAL 7023", nazov: "Betónová sivá", hex: "#686C5E", skupina: "greys" },
  { kod: "RAL 7024", nazov: "Grafitovo sivá", hex: "#3E3B39", skupina: "greys" },
  { kod: "RAL 7026", nazov: "Granitová sivá", hex: "#2F353B", skupina: "greys" },
  { kod: "RAL 7030", nazov: "Kamennosivá", hex: "#8B8C7A", skupina: "greys" },
  { kod: "RAL 7031", nazov: "Modrosivá", hex: "#474B4E", skupina: "greys" },
  { kod: "RAL 7032", nazov: "Štrkosivá", hex: "#B9B9A8", skupina: "greys" },
  { kod: "RAL 7033", nazov: "Cementová sivá", hex: "#7D8471", skupina: "greys" },
  { kod: "RAL 7034", nazov: "Žltosivá", hex: "#8F8B66", skupina: "greys" },
  { kod: "RAL 7035", nazov: "Svetlosivá", hex: "#D7D7D7", skupina: "greys" },
  { kod: "RAL 7036", nazov: "Platinovo sivá", hex: "#7F7679", skupina: "greys" },
  { kod: "RAL 7037", nazov: "Prachovo sivá", hex: "#7D7F7D", skupina: "greys" },
  { kod: "RAL 7038", nazov: "Achátsivá", hex: "#B5B8B1", skupina: "greys" },
  { kod: "RAL 7039", nazov: "Kremenná sivá", hex: "#6C6960", skupina: "greys" },
  { kod: "RAL 7040", nazov: "Okenná sivá", hex: "#9DA1AA", skupina: "greys" },
  { kod: "RAL 7042", nazov: "Dopravná sivá A", hex: "#8F949B", skupina: "greys" },
  { kod: "RAL 7043", nazov: "Dopravná sivá B", hex: "#4E5451", skupina: "greys" },
  { kod: "RAL 7044", nazov: "Hodvábna sivá", hex: "#CAC4B0", skupina: "greys" },
  { kod: "RAL 7045", nazov: "Telegrafická sivá 1", hex: "#8F8F8C", skupina: "greys" },
  { kod: "RAL 7046", nazov: "Telegrafická sivá 2", hex: "#82898F", skupina: "greys" },
  { kod: "RAL 7047", nazov: "Telegrafická sivá 4", hex: "#D0D0D0", skupina: "greys" },
  { kod: "RAL 7048", nazov: "Perlovo myšia", hex: "#898176", skupina: "greys" },
  { kod: "RAL 9006", nazov: "Biely hliník", hex: "#A5A5A5", skupina: "greys" },
  { kod: "RAL 9007", nazov: "Sivý hliník", hex: "#8F8F8F", skupina: "greys" },
  { kod: "RAL 9022", nazov: "Perlovo svetlosivá", hex: "#9C9C9C", skupina: "greys" },
  { kod: "RAL 9023", nazov: "Perlovo tmavosivá", hex: "#828282", skupina: "greys" },

  // BEIGES / BROWNS
  { kod: "RAL 1000", nazov: "Zeleno-béžová", hex: "#BEBD7F", skupina: "beiges-browns" },
  { kod: "RAL 1001", nazov: "Béžová", hex: "#D0B084", skupina: "beiges-browns" },
  { kod: "RAL 1011", nazov: "Hnedo-béžová", hex: "#8E7B41", skupina: "beiges-browns" },
  { kod: "RAL 1019", nazov: "Šedo-béžová", hex: "#A48F7A", skupina: "beiges-browns" },
  { kod: "RAL 1035", nazov: "Perlovo béžová", hex: "#6A5D4D", skupina: "beiges-browns" },
  { kod: "RAL 8000", nazov: "Zeleno-hnedá", hex: "#826C34", skupina: "beiges-browns" },
  { kod: "RAL 8001", nazov: "Okrová hnedá", hex: "#9D622B", skupina: "beiges-browns" },
  { kod: "RAL 8002", nazov: "Signálna hnedá", hex: "#6C3B2A", skupina: "beiges-browns" },
  { kod: "RAL 8003", nazov: "Hlinková hnedá", hex: "#7B5141", skupina: "beiges-browns" },
  { kod: "RAL 8004", nazov: "Medená hnedá", hex: "#8E402A", skupina: "beiges-browns" },
  { kod: "RAL 8007", nazov: "Srnčia hnedá", hex: "#59351F", skupina: "beiges-browns" },
  { kod: "RAL 8008", nazov: "Olivovo hnedá", hex: "#6F4F28", skupina: "beiges-browns" },
  { kod: "RAL 8011", nazov: "Orechovo hnedá", hex: "#5B3A29", skupina: "beiges-browns" },
  { kod: "RAL 8012", nazov: "Červeno-hnedá", hex: "#592321", skupina: "beiges-browns" },
  { kod: "RAL 8014", nazov: "Sépiová hnedá", hex: "#382C1E", skupina: "beiges-browns" },
  { kod: "RAL 8015", nazov: "Gaštanovo hnedá", hex: "#633A34", skupina: "beiges-browns" },
  { kod: "RAL 8016", nazov: "Mahagónová hnedá", hex: "#4C2F27", skupina: "beiges-browns" },
  { kod: "RAL 8017", nazov: "Čokoládovo hnedá", hex: "#45322E", skupina: "beiges-browns" },
  { kod: "RAL 8019", nazov: "Sivo-hnedá", hex: "#403A3A", skupina: "beiges-browns" },
  { kod: "RAL 8022", nazov: "Čierno-hnedá", hex: "#1A1718", skupina: "beiges-browns" },
  { kod: "RAL 8023", nazov: "Oranžovo-hnedá", hex: "#A65E2E", skupina: "beiges-browns" },
  { kod: "RAL 8024", nazov: "Béžovo-hnedá", hex: "#826C34", skupina: "beiges-browns" },
  { kod: "RAL 8025", nazov: "Bledá hnedá", hex: "#755C48", skupina: "beiges-browns" },
  { kod: "RAL 8028", nazov: "Terakotová hnedá", hex: "#4E3B31", skupina: "beiges-browns" },
  { kod: "RAL 8029", nazov: "Perlovo medená", hex: "#763C28", skupina: "beiges-browns" },

  // BLACKS
  { kod: "RAL 9004", nazov: "Signálna čierna", hex: "#1E1E1E", skupina: "blacks" },
  { kod: "RAL 9005", nazov: "Hĺbková čierna", hex: "#0A0A0A", skupina: "blacks" },
  { kod: "RAL 9011", nazov: "Grafitová čierna", hex: "#27292B", skupina: "blacks" },
  { kod: "RAL 9017", nazov: "Dopravná čierna", hex: "#1E1E1E", skupina: "blacks" },
];

export const RAL_GROUPS: { key: RalSwatch["skupina"]; label: string }[] = [
  { key: "whites", label: "Biele a ivory" },
  { key: "yellows-oranges", label: "Žlté a oranžové" },
  { key: "reds-pinks", label: "Červené a ružové" },
  { key: "violets", label: "Fialové" },
  { key: "blues", label: "Modré" },
  { key: "greens", label: "Zelené" },
  { key: "greys", label: "Sivé" },
  { key: "beiges-browns", label: "Béžové a hnedé" },
  { key: "blacks", label: "Čierne" },
];
